feat: pretty print HTML
stjude-rust-labs/wdl pull request #270
Opened 2024-12-16 21:50 UTC by a-frantz

_Describe the problem or feature in addition to a link to the issues._

Update `wdl-doc` to pretty print HTML. Achieved via the `Debug` format of the `html` crate.

Before submitting this PR, please make sure:

- [ ] You have added a few sentences describing the PR here.
- [ ] You have added yourself or the appropriate individual as the assignee.
- [ ] You have added at least one relevant code reviewer to the PR.
- [ ] Your code builds clean without any errors or warnings.
- [ ] You have added tests (when appropriate).
- [ ] You have updated the README or other documentation to account for these
      changes (when appropriate).
- [ ] You have added an entry to the relevant `CHANGELOG.md` (see
      ["keep a changelog"] for more information).
- [ ] Your commit messages follow the [conventional commit] style.

[conventional commit]: https://www.conventionalcommits.org/en/v1.0.0/#summary
["keep a changelog"]: https://keepachangelog.com/en/1.0.0/

2024-12-16 22:55 UTC, claymcleod commented on wdl-doc/CHANGELOG.md
> +* Pretty print HTML ([#270](https://github.com/stjude-rust-labs/wdl/pull/270)).
```suggestion
* Updates HTML generation to be pretty printed ([#270](https://github.com/stjude-rust-labs/wdl/pull/270)).
```

2024-12-16 22:56 UTC, claymcleod commented on wdl-doc/tests/output_docs/data_structures/flag_filter/FlagFilter-struct.html
> +</h1><ul>
Seems like this needs some newlines.

2024-12-16 22:56 UTC, claymcleod requested changes
Let's see what the results look like when you add the newline to the print statements.

2025-01-15 18:42 UTC, peterhuene commented
This generally looks good, but from https://github.com/yoshuawuyts/html/issues/60 I worry that we shouldn't rely on the `Debug` impl to pretty print it as it might introduce unintentional semantic whitespace.

Seems like the pretty printing is helpful for debugging the output of the `html` crate and not something we should rely on for pretty printing with fidelity.

2025-01-23 15:57 UTC, claymcleod commented
Okay, I think that's a fair criticism. I'm fine with closing this.

2025-01-23 15:59 UTC, closed without merging