feat: new lint-rule.md rule, 'header_comment"
stjude-rust-labs/wdl pull request #7
Opened 2024-02-27 17:55 UTC by a-frantz

Pretty straight-forward rule. Essentially, `##` comments are neato and you should use them! **But only in the header** all other places these are found will get a warning.

2024-02-27 20:17 UTC, adthrasher requested changes

2024-02-27 20:17 UTC, adthrasher commented on lint-rules.md
> +`sprocket doc` is under active development at the time of writing. This tool will auto-document any WDL file in MarkDown. Header-comments found by `sprocket doc` will be re-written in the output `.md
```suggestion
`sprocket doc` is under active development at the time of writing. This tool will auto-document any WDL file in Markdown. Header-comments found by `sprocket doc` will be re-written in the output `.md` files (without the `##` prefix). Arbitrary and multi-line Markdown constructions will be preserved and rendered.
```

2024-02-27 20:17 UTC, adthrasher commented on lint-rules.md
> +These header-comments should not be used anywhere beside the header.
```suggestion
These header-comments should not be used anywhere other than the header.
```

2024-02-27 20:17 UTC, adthrasher commented on lint-rules.md
> +These header-comments should not be used anywhere beside the header.
Maybe prefix with "As the name suggests, "

2024-02-27 20:24 UTC, a-frantz commented
@adthrasher IDK why the CI lint is failing, but IMO if all the code-tests are passing it's fine to merge this doc change. I think it would be inappropriate to make code changes in this PR.

2024-04-11 15:20 UTC, a-frantz commented on lint-rules.md
> +These header-comments should not be used anywhere other than the header.
Good point. I'll make that edit.

2024-04-11 16:33 UTC, adthrasher approved these changes

2024-04-11 17:47 UTC, merged